name: simple-oauth-server
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
description: Test server deployment
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
